// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:profinans/data/models/app_group.dart';
import 'package:profinans/data/models/app_settings.dart';
import 'package:profinans/data/models/category.dart';
import 'package:profinans/data/models/enums.dart';
import 'package:profinans/data/models/transaction.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppGroupAdapter());
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurrenceRuleAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppGroupAdapter());
    registerAdapter(AppSettingsAdapter());
    registerAdapter(CategoryAdapter());
    registerAdapter(RecurrenceRuleAdapter());
    registerAdapter(TransactionAdapter());
    registerAdapter(TransactionTypeAdapter());
  }
}
